// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePolicyData, CreatePolicyErrors, CreatePolicyResponses, DeletePolicyData, DeletePolicyErrors, DeletePolicyResponses, GetAgentData, GetAgentErrors, GetAgentResponses, GetAgentTasksData, GetAgentTasksErrors, GetAgentTasksResponses, GetComplianceOverviewData, GetComplianceOverviewErrors, GetComplianceOverviewResponses, GetReportDetailsData, GetReportDetailsErrors, GetReportDetailsResponses, GetScapContentData, GetScapContentErrors, GetScapContentResponses, ListAgentsData, ListAgentsErrors, ListAgentsResponses, ListPoliciesData, ListPoliciesErrors, ListPoliciesResponses, ListReportsData, ListReportsErrors, ListReportsResponses, LoginData, LoginErrors, LoginResponses, RegisterAgentData, RegisterAgentErrors, RegisterAgentResponses, UpdatePolicyData, UpdatePolicyErrors, UpdatePolicyResponses, UploadReportData, UploadReportErrors, UploadReportResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Register a new agent
 */
export const registerAgent = <ThrowOnError extends boolean = false>(options: Options<RegisterAgentData, ThrowOnError>): RequestResult<RegisterAgentResponses, RegisterAgentErrors, ThrowOnError> => (options.client ?? client).post<RegisterAgentResponses, RegisterAgentErrors, ThrowOnError>({
    url: '/agents/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch pending tasks and policy assignments for an agent
 */
export const getAgentTasks = <ThrowOnError extends boolean = false>(options: Options<GetAgentTasksData, ThrowOnError>): RequestResult<GetAgentTasksResponses, GetAgentTasksErrors, ThrowOnError> => (options.client ?? client).get<GetAgentTasksResponses, GetAgentTasksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/agents/{agentId}/tasks',
    ...options
});

/**
 * Upload an OpenSCAP XML report
 */
export const uploadReport = <ThrowOnError extends boolean = false>(options: Options<UploadReportData, ThrowOnError>): RequestResult<UploadReportResponses, UploadReportErrors, ThrowOnError> => (options.client ?? client).post<UploadReportResponses, UploadReportErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/agents/{agentId}/reports',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Download a specific SCAP data stream
 */
export const getScapContent = <ThrowOnError extends boolean = false>(options: Options<GetScapContentData, ThrowOnError>): RequestResult<GetScapContentResponses, GetScapContentErrors, ThrowOnError> => (options.client ?? client).get<GetScapContentResponses, GetScapContentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/scap/content/{contentId}',
    ...options
});

/**
 * List all registered agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>): RequestResult<ListAgentsResponses, ListAgentsErrors, ThrowOnError> => (options?.client ?? client).get<ListAgentsResponses, ListAgentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/agents',
    ...options
});

/**
 * Retrieve specific agent details
 */
export const getAgent = <ThrowOnError extends boolean = false>(options: Options<GetAgentData, ThrowOnError>): RequestResult<GetAgentResponses, GetAgentErrors, ThrowOnError> => (options.client ?? client).get<GetAgentResponses, GetAgentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/agents/{agentId}',
    ...options
});

/**
 * Get aggregate fleet compliance score
 */
export const getComplianceOverview = <ThrowOnError extends boolean = false>(options?: Options<GetComplianceOverviewData, ThrowOnError>): RequestResult<GetComplianceOverviewResponses, GetComplianceOverviewErrors, ThrowOnError> => (options?.client ?? client).get<GetComplianceOverviewResponses, GetComplianceOverviewErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/compliance/overview',
    ...options
});

/**
 * List historical compliance reports
 */
export const listReports = <ThrowOnError extends boolean = false>(options?: Options<ListReportsData, ThrowOnError>): RequestResult<ListReportsResponses, ListReportsErrors, ThrowOnError> => (options?.client ?? client).get<ListReportsResponses, ListReportsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/compliance/reports',
    ...options
});

/**
 * Get detailed view of a specific compliance report
 */
export const getReportDetails = <ThrowOnError extends boolean = false>(options: Options<GetReportDetailsData, ThrowOnError>): RequestResult<GetReportDetailsResponses, GetReportDetailsErrors, ThrowOnError> => (options.client ?? client).get<GetReportDetailsResponses, GetReportDetailsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/compliance/reports/{reportId}',
    ...options
});

/**
 * List defined policies
 */
export const listPolicies = <ThrowOnError extends boolean = false>(options?: Options<ListPoliciesData, ThrowOnError>): RequestResult<ListPoliciesResponses, ListPoliciesErrors, ThrowOnError> => (options?.client ?? client).get<ListPoliciesResponses, ListPoliciesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/policies',
    ...options
});

/**
 * Create a new policy
 */
export const createPolicy = <ThrowOnError extends boolean = false>(options: Options<CreatePolicyData, ThrowOnError>): RequestResult<CreatePolicyResponses, CreatePolicyErrors, ThrowOnError> => (options.client ?? client).post<CreatePolicyResponses, CreatePolicyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/policies',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a policy
 */
export const deletePolicy = <ThrowOnError extends boolean = false>(options: Options<DeletePolicyData, ThrowOnError>): RequestResult<DeletePolicyResponses, DeletePolicyErrors, ThrowOnError> => (options.client ?? client).delete<DeletePolicyResponses, DeletePolicyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/policies/{policyId}',
    ...options
});

/**
 * Update a policy
 */
export const updatePolicy = <ThrowOnError extends boolean = false>(options: Options<UpdatePolicyData, ThrowOnError>): RequestResult<UpdatePolicyResponses, UpdatePolicyErrors, ThrowOnError> => (options.client ?? client).put<UpdatePolicyResponses, UpdatePolicyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/policies/{policyId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Issue JWT token for dashboard users
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
