// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type AgentRegistration = {
    hostname: string;
    os_name: string;
    os_version: string;
    architecture: string;
};

export type AgentRegistrationResponse = {
    id: string;
    token: string;
};

export type AgentTasksResponse = {
    tasks: Array<AgentTask>;
};

export type AgentTask = {
    task_id: string;
    content_id: string;
    profile_id: string;
};

export type Agent = {
    id: string;
    hostname: string;
    os_name: string;
    os_version: string;
    architecture?: string;
    last_seen: string;
};

export type ComplianceOverview = {
    total_agents: number;
    compliant_agents: number;
    non_compliant_agents: number;
    average_score: number;
};

export type ReportSummary = {
    id: string;
    agent_id: string;
    timestamp: string;
    score: number;
};

export type ReportDetails = {
    id: string;
    summary: ReportSummary;
    rule_results: Array<RuleResult>;
};

export type RuleResult = {
    rule_id: string;
    result: 'pass' | 'fail' | 'error' | 'unknown' | 'notapplicable';
    severity?: string;
};

export type Policy = {
    id: string;
    name: string;
    os_target: string;
    content_id: string;
    profile_id: string;
};

export type PolicyCreate = {
    name: string;
    os_target: string;
    content_id: string;
    profile_id: string;
};

export type PolicyUpdate = {
    name?: string;
    os_target?: string;
    content_id?: string;
    profile_id?: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type LoginResponse = {
    access_token: string;
};

export type RegisterAgentData = {
    body: AgentRegistration;
    path?: never;
    query?: never;
    url: '/agents/register';
};

export type RegisterAgentErrors = {
    /**
     * Invalid request parameters or body
     */
    400: unknown;
};

export type RegisterAgentResponses = {
    /**
     * Successfully registered
     */
    201: AgentRegistrationResponse;
};

export type RegisterAgentResponse = RegisterAgentResponses[keyof RegisterAgentResponses];

export type GetAgentTasksData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/tasks';
};

export type GetAgentTasksErrors = {
    /**
     * Authentication required
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
};

export type GetAgentTasksResponses = {
    /**
     * Pending tasks
     */
    200: AgentTasksResponse;
};

export type GetAgentTasksResponse = GetAgentTasksResponses[keyof GetAgentTasksResponses];

export type UploadReportData = {
    body: {
        report?: Blob | File;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/reports';
};

export type UploadReportErrors = {
    /**
     * Invalid request parameters or body
     */
    400: unknown;
    /**
     * Authentication required
     */
    401: unknown;
};

export type UploadReportResponses = {
    /**
     * Report accepted for processing
     */
    202: unknown;
};

export type GetScapContentData = {
    body?: never;
    path: {
        contentId: string;
    };
    query?: never;
    url: '/scap/content/{contentId}';
};

export type GetScapContentErrors = {
    /**
     * Authentication required
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
};

export type GetScapContentResponses = {
    /**
     * SCAP XML or ZIP data stream
     */
    200: Blob | File;
};

export type GetScapContentResponse = GetScapContentResponses[keyof GetScapContentResponses];

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents';
};

export type ListAgentsErrors = {
    /**
     * Authentication required
     */
    401: unknown;
};

export type ListAgentsResponses = {
    /**
     * List of agents
     */
    200: Array<Agent>;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type GetAgentData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type GetAgentErrors = {
    /**
     * Authentication required
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
};

export type GetAgentResponses = {
    /**
     * Agent details
     */
    200: Agent;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type GetComplianceOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/compliance/overview';
};

export type GetComplianceOverviewErrors = {
    /**
     * Authentication required
     */
    401: unknown;
};

export type GetComplianceOverviewResponses = {
    /**
     * Compliance overview stats
     */
    200: ComplianceOverview;
};

export type GetComplianceOverviewResponse = GetComplianceOverviewResponses[keyof GetComplianceOverviewResponses];

export type ListReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/compliance/reports';
};

export type ListReportsErrors = {
    /**
     * Authentication required
     */
    401: unknown;
};

export type ListReportsResponses = {
    /**
     * List of reports
     */
    200: Array<ReportSummary>;
};

export type ListReportsResponse = ListReportsResponses[keyof ListReportsResponses];

export type GetReportDetailsData = {
    body?: never;
    path: {
        reportId: string;
    };
    query?: never;
    url: '/compliance/reports/{reportId}';
};

export type GetReportDetailsErrors = {
    /**
     * Authentication required
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
};

export type GetReportDetailsResponses = {
    /**
     * Detailed compliance report
     */
    200: ReportDetails;
};

export type GetReportDetailsResponse = GetReportDetailsResponses[keyof GetReportDetailsResponses];

export type ListPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/policies';
};

export type ListPoliciesErrors = {
    /**
     * Authentication required
     */
    401: unknown;
};

export type ListPoliciesResponses = {
    /**
     * List of policies
     */
    200: Array<Policy>;
};

export type ListPoliciesResponse = ListPoliciesResponses[keyof ListPoliciesResponses];

export type CreatePolicyData = {
    body: PolicyCreate;
    path?: never;
    query?: never;
    url: '/policies';
};

export type CreatePolicyErrors = {
    /**
     * Invalid request parameters or body
     */
    400: unknown;
    /**
     * Authentication required
     */
    401: unknown;
};

export type CreatePolicyResponses = {
    /**
     * Created policy
     */
    201: Policy;
};

export type CreatePolicyResponse = CreatePolicyResponses[keyof CreatePolicyResponses];

export type DeletePolicyData = {
    body?: never;
    path: {
        policyId: string;
    };
    query?: never;
    url: '/policies/{policyId}';
};

export type DeletePolicyErrors = {
    /**
     * Authentication required
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
};

export type DeletePolicyResponses = {
    /**
     * Policy deleted
     */
    204: void;
};

export type DeletePolicyResponse = DeletePolicyResponses[keyof DeletePolicyResponses];

export type UpdatePolicyData = {
    body: PolicyUpdate;
    path: {
        policyId: string;
    };
    query?: never;
    url: '/policies/{policyId}';
};

export type UpdatePolicyErrors = {
    /**
     * Invalid request parameters or body
     */
    400: unknown;
    /**
     * Authentication required
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
};

export type UpdatePolicyResponses = {
    /**
     * Updated policy
     */
    200: Policy;
};

export type UpdatePolicyResponse = UpdatePolicyResponses[keyof UpdatePolicyResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Authentication required
     */
    401: unknown;
};

export type LoginResponses = {
    /**
     * Authentication successful
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];
