apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: aegis
type: Opaque
stringData:
  POSTGRES_USER: aegis
  POSTGRES_PASSWORD: aegis_password
  POSTGRES_DB: aegis_fleetscope
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: aegis
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: aegis
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
